global:
  # How frequently to scrape targets by default.
  scrape_interval: 1m
  scrape_timeout: 20s

scrape_configs:

  - job_name: "homeassistant"
    scrape_interval: 30s
    metrics_path: /api/prometheus
    bearer_token: "add-your-token-here"

    scheme: http
    static_configs:
      - targets: ['localhost:8123']
